title: "App dashboard"
subtitle: "Homer"
logo: "assets/logo.png"
header: false
footer: ''
columns: "auto"
connectivityCheck: true
defaults:
  layout: columns
  colorTheme: auto
theme: default
services:
  - name: "Media"
    icon: "fas fa-cloud"
    items:
      - name: "Jellyfin"
        subtitle: "Media Streaming Server"
        tag: "media"
        type: "Emby"
        apikey: ""
        url: "http://192.168.188.44:8096"
        target: "_blank"
      - name: "Jellyseerr"
        subtitle: "Media Request Tool"
        tag: "media"
        url: "http://192.168.188.44:5055"
        target: "_blank"
      - name: "Yarr"
        subtitle: "RSS Reader"
        tag: "media"
        url: "http://192.168.188.44:7070"
        target: "_blank"
      - name: "Nextcloud"
        subtitle: "Personal Cloud Storage"
        tag: "media"
        url: "https://nextcloud.desimedia.duckdns.org"
        target: "_blank"
  - name: "Downloads"
    icon: "fas fa-cloud-download-alt"
    items:
      - name: "Sonarr"
        subtitle: "TV Show Indexer"
        tag: "downloads"
        url: "http://192.168.188.44:8989"
        type: "Sonarr"
        apikey: ""
        target: "_blank"
      - name: "Radarr"
        subtitle: "Movie Indexer"
        type: "Radarr"
        apikey: ""
        tag: "downloads"
        url: "http://192.168.188.44:7878"
        target: "_blank"
      - name: "Prowlarr"
        subtitle: "Movie and TV Show Indexer"
        tag: "downloads"
        type: "Prowlarr"
        apikey: ""
        url: "http://192.168.188.44:9696"
        target: "_blank"
      - name: "Transmission"
        subtitle: "Torrent Client"
        tag: "downloads"
        url: "http://192.168.188.44:9091/transmission/web/"
        target: "_blank"
  - name: "Utilities"
    icon: "fas fa-tools"
    items:
      - name: "Duplicati"
        subtitle: "Backup Client"
        tag: "utilities"
        url: "http://192.168.188.44:8200"
        target: "_blank"
      - name: "Gogs"
        subtitle: "Git Hosting"
        tag: "utilities"
        url: "http://192.168.188.44:3000"
        target: "_blank"
      - name: "Speedtest Tracker"
        subtitle: "Internet Speed Test Tracker"
        tag: "utilities"
        url: "http://192.168.188.44:8765"
        target: "_blank"
      - name: "Glances"
        subtitle: "System monitor"
        tag: "utilities"
        url: "http://192.168.188.44:61208"
        target: "_blank"
      - name: "Filebrowser"
        subtitle: "Web interface file browser"
        tag: "utilities"
        url: "http://192.168.188.44:8080"
        target: "_blank"
  - name: "Other"
    icon: "fas fa-cog"
    items:
      - name: "FlareSolverr"
        subtitle: "Captcha Solver"
        tag: "utilities"
        url: "http://192.168.188.44:8191"
        target: "_blank"
      - name: "Nginx Proxy Manager"
        subtitle: "Reverse Proxy"
        tag: "proxy"
        url: "http://192.168.188.44:81/login"
        target: "_blank"
      - name: "Scrutiny"
        subtitle: "Hard Drive S.M.A.R.T Monitoring"
        tag: "Monitoring"
        url: "http://192.168.188.44:8081"
        target: "_blank"
      - name: "Home Assistant"
        subtitle: "Smart Home Automation"
        tag: "smart-home"
        url: "http://192.168.188.44:8123"
        target: "_blank"
